### ISSUE TITLE
Cycled increments and decrements

### ISSUE THREAD

**Issue by KozlovKV** [KozlovKV/game-life#11]
**It's so reasonable to use bit operators instead of `if`s**

Create 2 macroses:
- [ ] cycled increment for values from 0 to 7 (3 lower bits)
- [ ] cycled decrement for values from 0 to 7 (3 lower bits)

**Comment by PalkinEgor** [comment]
@KozlovKV также сделал в отдельных файлах asm, branch - cycled_inc_dec
