### ISSUE TITLE
Bit getter and inverter

### ISSUE THREAD

**Issue by KozlovKV** [KozlovKV/game-life#14]
**WORK ON BRANCH `asm/byte-processing`**

**SEE PSEUDO VERSION [HERE](https://github.com/KozlovKV/game-life/blob/master/tech-info.md#псевдокод)**

**Also use bit operators everywhere you can**

2 subroutines:
1. `getBit` - gets the `i`th bit (index in `r1`) of byte from `r0` and return it to `r0`
2. `invertBit` - inverts bit on the `i`th position (index in `r1`) in byte from `r0` and return it to `r0` (other bits must not be changed)

**Comment by PalkinEgor** [comment]
@KozlovKV сделал в отдельном файле branch - bit_getter_inverter
