### ISSUE TITLE
New bit in byte processing

### ISSUE THREAD

**Issue by KozlovKV** [KozlovKV/game-life#29]
**WORK ON BRANCH `asm/byte-processing`**

**SEE PSEUDO VERSION [HERE](https://github.com/KozlovKV/game-life/blob/master/tech-info.md#псевдокод)**

Create function `processBitInByte` that will change or not bit with index from `r1` in byte from `r0` depending on surrounding sum from `r2` and conditions of birth or death

**Comment by PalkinEgor** [comment]
@KozlovKV сделал в отдельном файле, branch - bit_proccesing

**Comment by KozlovKV** [comment]
1. Add loading from conditional addresses
2. Don't rewrite value in `r1` before the last `if` (so reasonable to use `tst` and `z`/`nz`)

**Comment by PalkinEgor** [comment]
@KozlovKV вроде пофиксил
