### ISSUE TITLE
Refactor logisim bit invertre

### ISSUE THREAD

**Issue by KozlovKV** [KozlovKV/game-life#32]
Refactor bit_inverter circuit:
- All inputs on the **left** side in column
- All outputs on the **right** side in column
- Use wires and tunnels (**not only one of them**)
- **Check appearance after refactoring. It must be unchanged**

**Comment by PalkinEgor** [comment]
@KozlovKV загрузил как библиотеку logisim в проект, branch - new_bit_inertor
