### ISSUE TITLE
Create game modes switcher

### ISSUE THREAD

**Issue by KozlovKV** [KozlovKV/game-life#6]
Initial state - `0` (setting state).

When button was pressed state changes to `1` and saves to I/O register `0xf0`.

After it these inputs must be blocked:
- I/O reg. `0xf0` (we cannot switch from state `1` to state `0`)
- I/O regs. `0xf1`, `0xf2` (bit arrs. of birth and stay conditions)
- Keyboard input (input for selecting row on video buffer must listen to the other wire using multiplexer (*wiil be soon*))
- `switch` input of bit inverter (permanent `0`)

Connect 2 tunnels on game-mode reg. output: `setting` (`1` when reg. output = `0`) and `playing` (`1` when reg. output = `1`)

**Comment by PalkinEgor** [comment]
Complete task in branch <game_settings>
