### ISSUE TITLE
Game rules registers

### ISSUE THREAD

**Issue by KozlovKV** [KozlovKV/game-life#7]
2 I/O registers that watch on 2 8-bit inputs that updates while `setting` is 1 (see #6):
- `0xf1` - birth conditions 
- `0xf2` - death conditions (inverts bits from input)

Thus, regs' triggers depends on `clock` and `setting`

**Comment by PalkinEgor** [comment]
@KozlovKV complete this task, branch rules_registers

**Comment by KozlovKV** [comment]
@PalkinEgor , значение deathConditions - это не инверсия значения birthConditions. Это отдельный вход, который инвертирует условия продолжения жизни из базовой игры (они ведь там задаются чем-то вроде B2 / S23, то есть при таких условиях у нас будет:
- birthInput = 00000010 => birthConditions = 00000010 
- stayInput = 00000110 => deathConditions = 11111001

**Comment by PalkinEgor** [comment]
fix this
